### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ziadoz** [ziadoz/awesome-php#46]
**Future Improvements**
- [x] Split out Text and Numbers category into Strings and Numbers.
- [x] Add Configuration category.
- [x] Add Functional Programming category.
- [x] Break out Code Analysis into Debugging where applicable.
- [x] Rename ORM and Datamapper category to Database.
- [x] Split out password libraries into own category.
- [x] ~~Add all major PHP framework components to the list (https://github.com/ziadoz/awesome-php/issues/90).~~
- [ ] Add C/PECL extensions category (https://github.com/ziadoz/awesome-php/issues/2).
- [ ] ~~Display license for each project (https://github.com/ziadoz/awesome-php/issues/14)~~.
- [x] ~~Add community members section.~~
- [ ] Add a conferences section.
- [x] ~~Add Framework Bundles category (SF2, LV4, ZF2)~~.
- [ ] Build a website for the project (https://github.com/ziadoz/awesome-php/issues/94). Flatfiles. JSON files. Compiled into a website via a template.
- [x] ~~Work out how to support multiple languages (possibly related to building a website).~~
- [x] Move 'Contributing' text to the top of the document (https://github.com/ziadoz/awesome-php/pull/220).
- [x] Go through all categories and perform a cleanup and cull.
- [ ] Add legend/dagger for paid components and framework components.
- [x] Remove PHP Reading (often end up outdated), Other Websites and ~~Other Books (too broad)~~ sections. ***
- [ ] Add a pull request template.
- [ ] Link to other Awesome PHP lists (https://github.com/FriendsOfCake/awesome-cakephp, https://github.com/jakoch/awesome-composer).
- [ ] Add Awesome branding badge.
- [ ] Consider Github discussions section.

**Comment by ziadoz** [comment]
French PHP Resources: https://github.com/ziadoz/awesome-php/pull/334 https://github.com/ziadoz/awesome-php/pull/335

**Comment by IvanDelsinne** [comment]
@ziadoz about framework components, why not make a subdirectory of md files, each of them dedicated to a framework and listing components with some infos like the README.md ?

**Comment by dereuromark** [comment]
Or those frameworks project their own list you can link to - e.g. [awesome-cakephp](https://github.com/FriendsOfCake/awesome-cakephp) for  [CakePHP](https://github.com/cakephp/cakephp). Depends on the framework and if they already have their own list. Ideally, the frameworks should own those specific lists, and it will also be less work for you to mainain them (they would otherwise become outdated over time).

**Comment by rudinandrey** [comment]
https://fatfreeframework.com/3.6/home look at this amazing framework F3. This is the best of the best :-)

**Comment by ziadoz** [comment]
> Or those frameworks project their own list you can link to - e.g. [awesome-cakephp](https://github.com/FriendsOfCake/awesome-cakephp) for [CakePHP](https://github.com/cakephp/cakephp). Depends on the framework and if they already have their own list. Ideally, the frameworks should own those specific lists, and it will also be less work for you to mainain them (they would otherwise become outdated over time).

@dereuromark Linking to separate awesome lists for framework specific bits sounds like good. If you open a PR I'll take a look. Thanks!

**Comment by aman00323** [comment]
@ziadoz I have a thought in my mind to make this package more accurate.

- Some of the packages might have not been maintained for too long or they have been archived.

**Suggestion**

- We will have a cron job running which will be checking for the last commit, archived or not, etc.
- If it is been archived and most popular then we can have a separate section there which will be automatically updated by the bot. (which we need to develop :smile: )
- Also we can display when the last version is released beside package names.

Let me know what do you think about this idea.

**Comment by ziadoz** [comment]
@aman00323 What you are suggesting is an interesting idea, and it's something that has crossed my mind - I actually wrote a prototype, a long time ago. However, I think it's beyond the scope of this project. I already struggle to maintain this list in a timely manner, without the addition of code.

Perhaps it would be better to open an issue or pull request on the [Awesome Bot](https://github.com/dkhamsing/awesome_bot) repository? That's the bot we use to validate links in our Github Actions workflow. Then other Awesome Lists can benefit from the same functionality. Thanks.

**Comment by periurium** [comment]
[Bramus Router](https://github.com/bramus/router) is a good router to use, one that I have been using in some of my projects. A little older but not a bad option

**Comment by nthhanh526** [comment]
**dot
**@.doc
